import type { CapacitorConfig } from "@capacitor/cli";

/**
 * IMUSIC Android shell.
 *
 * The APK is a thin native wrapper around the published web app, so web
 * releases ship instantly and a new APK is only needed for native changes
 * (icons, permissions, Capacitor upgrades).
 */
const config: CapacitorConfig = {
  appId: "app.lovable.imusic",
  appName: "IMUSIC",
  // Offline fallback bundle generated by the release workflow.
  webDir: "dist-android",
  android: {
    allowMixedContent: false,
    backgroundColor: "#0A0A0B",
  },
  server: {
    url: "https://sonic-bloom-63.lovable.app",
    cleartext: false,
    androidScheme: "https",
  },
};

export default config;
