import type { CapacitorConfig } from "@capacitor/cli";

/**
 * IMUSIC Android shell.
 *
 * The APK is a thin native wrapper around the published web app, so web
 * releases ship instantly and a new APK is only needed for native changes
 * (icons, permissions, Capacitor upgrades).
 */
const config: CapacitorConfig = {
  appId: "app.lovable.imusic",
  appName: "IMUSIC",
  // Offline fallback bundle generated by the release workflow.
  webDir: "dist-android",
  android: {
    allowMixedContent: false,
    backgroundColor: "#0A0A0B",
    webContentsDebuggingEnabled: false,
    // Lets the web app detect the native shell (see src/lib/native/platform.ts).
    appendUserAgent: "IMUSICApp",
  },
  server: {
    url: "https://imusic-com.lovable.app",
    cleartext: false,
    androidScheme: "https",
  },
  plugins: {
    SplashScreen: {
      launchAutoHide: true,
      launchShowDuration: 800,
      backgroundColor: "#0A0A0B",
      androidSplashResourceName: "splash",
      showSpinner: false,
    },
    StatusBar: {
      style: "DARK",
      backgroundColor: "#0A0A0B",
      overlaysWebView: false,
    },
  },
};

export default config;
