/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistsIndexRouteImport } from './routes/artists/index'
import { Route as SpotifyCallbackRouteImport } from './routes/spotify/callback'
import { Route as ArtistsArtistIdRouteImport } from './routes/artists/$artistId'
import { Route as AuthenticatedLikedRouteImport } from './routes/_authenticated/liked'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPlaylistPlaylistIdRouteImport } from './routes/_authenticated/playlist.$playlistId'
import { Route as ApiPublicHooksYoutubeKeyHealthRouteImport } from './routes/api/public/hooks/youtube-key-health'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotifyCallbackRoute = SpotifyCallbackRouteImport.update({
  id: '/spotify/callback',
  path: '/spotify/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsArtistIdRoute = ArtistsArtistIdRouteImport.update({
  id: '/artists/$artistId',
  path: '/artists/$artistId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLikedRoute = AuthenticatedLikedRouteImport.update({
  id: '/liked',
  path: '/liked',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaylistPlaylistIdRoute =
  AuthenticatedPlaylistPlaylistIdRouteImport.update({
    id: '/playlist/$playlistId',
    path: '/playlist/$playlistId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksYoutubeKeyHealthRoute =
  ApiPublicHooksYoutubeKeyHealthRouteImport.update({
    id: '/api/public/hooks/youtube-key-health',
    path: '/api/public/hooks/youtube-key-health',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/liked': typeof AuthenticatedLikedRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/spotify/callback': typeof SpotifyCallbackRoute
  '/artists/': typeof ArtistsIndexRoute
  '/playlist/$playlistId': typeof AuthenticatedPlaylistPlaylistIdRoute
  '/api/public/hooks/youtube-key-health': typeof ApiPublicHooksYoutubeKeyHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/liked': typeof AuthenticatedLikedRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/spotify/callback': typeof SpotifyCallbackRoute
  '/artists': typeof ArtistsIndexRoute
  '/playlist/$playlistId': typeof AuthenticatedPlaylistPlaylistIdRoute
  '/api/public/hooks/youtube-key-health': typeof ApiPublicHooksYoutubeKeyHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/liked': typeof AuthenticatedLikedRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/spotify/callback': typeof SpotifyCallbackRoute
  '/artists/': typeof ArtistsIndexRoute
  '/_authenticated/playlist/$playlistId': typeof AuthenticatedPlaylistPlaylistIdRoute
  '/api/public/hooks/youtube-key-health': typeof ApiPublicHooksYoutubeKeyHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/sitemap.xml'
    | '/admin'
    | '/library'
    | '/liked'
    | '/artists/$artistId'
    | '/spotify/callback'
    | '/artists/'
    | '/playlist/$playlistId'
    | '/api/public/hooks/youtube-key-health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/search'
    | '/sitemap.xml'
    | '/admin'
    | '/library'
    | '/liked'
    | '/artists/$artistId'
    | '/spotify/callback'
    | '/artists'
    | '/playlist/$playlistId'
    | '/api/public/hooks/youtube-key-health'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/search'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/library'
    | '/_authenticated/liked'
    | '/artists/$artistId'
    | '/spotify/callback'
    | '/artists/'
    | '/_authenticated/playlist/$playlistId'
    | '/api/public/hooks/youtube-key-health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArtistsArtistIdRoute: typeof ArtistsArtistIdRoute
  SpotifyCallbackRoute: typeof SpotifyCallbackRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  ApiPublicHooksYoutubeKeyHealthRoute: typeof ApiPublicHooksYoutubeKeyHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotify/callback': {
      id: '/spotify/callback'
      path: '/spotify/callback'
      fullPath: '/spotify/callback'
      preLoaderRoute: typeof SpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$artistId': {
      id: '/artists/$artistId'
      path: '/artists/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof ArtistsArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/liked': {
      id: '/_authenticated/liked'
      path: '/liked'
      fullPath: '/liked'
      preLoaderRoute: typeof AuthenticatedLikedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playlist/$playlistId': {
      id: '/_authenticated/playlist/$playlistId'
      path: '/playlist/$playlistId'
      fullPath: '/playlist/$playlistId'
      preLoaderRoute: typeof AuthenticatedPlaylistPlaylistIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/youtube-key-health': {
      id: '/api/public/hooks/youtube-key-health'
      path: '/api/public/hooks/youtube-key-health'
      fullPath: '/api/public/hooks/youtube-key-health'
      preLoaderRoute: typeof ApiPublicHooksYoutubeKeyHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedLikedRoute: typeof AuthenticatedLikedRoute
  AuthenticatedPlaylistPlaylistIdRoute: typeof AuthenticatedPlaylistPlaylistIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedLikedRoute: AuthenticatedLikedRoute,
  AuthenticatedPlaylistPlaylistIdRoute: AuthenticatedPlaylistPlaylistIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArtistsArtistIdRoute: ArtistsArtistIdRoute,
  SpotifyCallbackRoute: SpotifyCallbackRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  ApiPublicHooksYoutubeKeyHealthRoute: ApiPublicHooksYoutubeKeyHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
